#!/bin/bash

# Import tools
. $DOT_DIR/shell/tools.sh

# Check system
sys_dir="$DOT_DIR/system"
if [ ! -d "$sys_dir" ]
then
    print_error "No system is currently selected!"
    exit 1
fi

# Set variables
sys_name=$(cat "$sys_dir/name.conf")
cmd_file="$sys_dir/commands.conf"

if [ ! -f "$cmd_file" ]
then
    print_error "The current system's commands file ($cmd_file) does not exist!"
    exit 1
fi

# Load all commands
cmd_str=$(cat $cmd_file | grep -E "(^\+)|(^\=)")
readarray -t cmd_arr <<<"$cmd_str"

unset cmd_names
unset cmd_cmds
for ((i = 0; i < $(( ${#cmd_arr[@]}/2 )); i++))
do
    cmd_names[$i]=${cmd_arr[$(( $i*2 ))]#+}
    cmd_cmds[$i]=${cmd_arr[$(( $i*2+1 ))]#=}
done

# Prepare menus
for ((i = 0; i < ${#cmd_names[@]}; i++))
do
    menu_args[$((2*i))]="(${i})"
    menu_args[$((2*i+1))]="${cmd_names[$i]}"
done


# Show menu
menu_result=$(whiptail --title "Select Command" --menu "" 30 50 20 "${menu_args[@]}" 3>&2 2>&1 1>&3)

if [ "$menu_result" == "" ]
then
    print_warning "Canceled!"
    exit 1
else
    # Get path to the system folder
    menu_nr=${menu_result/(/}
        menu_nr=${menu_nr/)/}
    cmd_name=${cmd_names[$menu_nr]}
    cmd_cmd=${cmd_cmds[$menu_nr]}

    eval "$cmd_cmd"
fi
